Fruity Blood Overdrive parser
demberto/PyFLP pull request #120
Opened 2023-02-25 10:37 UTC by ttaschke

* Adds a parser for `Fruity Blood Overdrive`
* Adds `.fst` file for testing `Fruity Blood Overdrive` parse testing

<img width="427" alt="Screen Shot 2023-02-25 at 19 36 39" src="https://user-images.githubusercontent.com/7067750/221352323-c6ca6761-3140-481c-b4b8-257be60ce698.png">

2023-02-25 10:42 UTC, ttaschke commented
@demberto 
This is a version with `construct` and the changes discussed in the draft PR.

I made the `plugin_marker` optional for now, as I was not able to get a `.fst` from an older plugin version. Also, I am still unsure how this would look like on a global (`StructEventBase`?) layer. Please let me know your thoughts on this.
https://github.com/demberto/PyFLP/pull/120/files#diff-7cbba45382f7949d6cb914fe5ee6fea2836260673dc3f868c15f2ae7ea0ce383R94

2023-02-26 11:00 UTC, demberto requested changes

2023-02-26 11:00 UTC, demberto commented on pyflp/plugin.py
> +        "plugin_marker" / c.Optional(c.Bytes(4)),  # redesigned native plugin marker
I have slightly changed the handling for `StructEventBase` in https://github.com/demberto/PyFLP/commit/bd493c2ac363af0efe768e7582de11b17ee9d265

A kwarg named `len` is passed to every construct by StructEventBase's ctor.

Use `c.If(c.this._.len == 33, c.Bytes(4))`. Also are you sure `x100` is just a single byte? I think Blood Overdrive's event was 36 bytes.
If it is, change the comparsion above to `c.this._.len == 36`.

2023-02-26 11:00 UTC, demberto commented on pyflp/plugin.py
> +    """Linear.
Please keep an empty line between "Linear." and the table. It causes issues with sphinx-autodoc.

2023-02-27 13:45 UTC, ttaschke commented on pyflp/plugin.py
> +    """Linear.
Fixed: a4ddc7e40ac9eba27ef6d43ef1fdef88018399f5

2023-02-27 13:49 UTC, ttaschke commented on pyflp/plugin.py
> +        "plugin_marker" / c.Optional(c.Bytes(4)),  # redesigned native plugin marker
Yes, you are right, `x100` should be 4 bytes and the total length 36 bytes.
Fixed in 1234acaf9eaeddd779d505ab0299672fdfa6dcfb.

2023-03-01 04:52 UTC, demberto commented
Perfect :)

2023-03-01 04:54 UTC, merged