fix: pan min/max can be up to 128
demberto/PyFLP pull request #9
Opened 2022-07-16 01:44 UTC by zacanger

Note pan can be -128—128. Tested simply by adding one note on the piano roll and using the piano roll pan editor all the way up/down. On FL v 20.9.2 (build 2459), Producer/All Plugins edition, on Apple Silicon mac 12.

2022-07-16 07:21 UTC, demberto commented
Thanks for your contributions :)

I am actually doing an entire rewrite rn, none of those commits are pushed but, I am going for a more standard property based approach. `_FLObject` was long pending a refactor anyways.

Does FL Studio on Mac use UTF16 as well?

2022-07-16 07:49 UTC, tochibedford commented
Is the rewrite going to cause issues with already written contributions @demberto

2022-07-16 14:25 UTC, zacanger commented
Good catch, I never really use Notebook2 or project info, so didn't notice that. Tested [this commit](c44b87bb99ae558f85a425ea1142b336118d4b38) with a Notebook2.

2022-07-16 15:56 UTC, demberto commented
@zacanger `TextEvent`s aren't encoded in UTF-8 in Mac, I just verified it with your test FLP. Notebook2's `DataEvent` might be using it on Mac. Also, the note pan min/max limits seem to be raised in 20.9 because my test FLP has similar notes with max/min pan.

> Please let me know if that change is idiomatic
They will be idiomatic as well, since now I am better at Python myself. But most importantly, the property values will not be generated by all the `parseprop` and `parse_event` mess. They will be deserialized by the property getters from corresponding event data and serialized back by the setters. I have created helper prototypes to reduce code duplication created by this.

Along with this, after the events are all collected into a list by `Parser`, they won't be sent to the `_FLObject`s one by one as they are now. I will introduce event collectors in between which will gather events required for creating every model. After the collectors create their own sublists, I will pass them to constructors of the model classes. These constructors won't do any operations on them and store them in a private variable to be used by the getter/setters.

Or, I have been thinking of other way where the model classes (Channel, Track etc.) could be just simple dataclasses and serialization/deserialization would fall in the hands of collectors.

Also, I need to be very careful about validators in the future, probably discard their use completely. FLP is a very broken format at its core. The fact that they get invoked while parsing (its a bug) is the source of many problems.

2022-07-16 17:49 UTC, zacanger commented
Thanks. I reverted the TextEvent change, left the one in Notebook2, but didn't touch DataEvent itself. I definitely look forward to your changes. I'm not surprised the FLP format is messy, since they've kept it mostly backwards-compatible for the last 24 years. It must be quite a chore keeping up with whatever Image Line are doing without good documentation on the format, so really, huge thanks for doing the work in this project :)

2022-07-21 15:28 UTC, demberto requested changes

2022-07-21 15:28 UTC, demberto commented on pyflp/pattern/note.py
> +    pan: int = _IntProperty(min_=-128, max_=128)
Max should be 127

2022-07-21 23:48 UTC, zacanger commented on pyflp/pattern/note.py
> +    pan: int = _IntProperty(min_=-128, max_=128)
Whoops, right you are!

2022-07-22 12:32 UTC, merged